
spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/products/**

---
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8081
          predicates:
            - Path=/orders/**
        - id: product
          uri: http://product:8082
          predicates:
            - Path=/products/**